Organize docs
NVIDIA/cuda-quantum pull request #1724
Opened 2024-05-29 10:27 UTC by WingCode

### Description

closes #1624

2024-05-29 10:46 UTC, WingCode commented
recheck

2024-05-29 10:47 UTC, WingCode commented
recheck

2024-06-03 19:57 UTC, efratshabtai commented
Thank you for the PR. Please add the C++ code snippets to the new files in the Examples folder, as mentioned in the issue #1624: "the code cells need to be moved into separate Python/C++ files either under [snippets](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/snippets) (for small code blocks) or under [examples](https://github.com/NVIDIA/cuda-quantum/tree/main/docs/sphinx/examples) (for larger, more interesting code examples).

2024-06-03 20:56 UTC, efratshabtai requested changes
Thank you for the PR, please take a look at my comments and suggestions.

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/quantum_operations.rst
> +
It will be nice to add print(cudaq.draw(kernel)) here too.

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +    # for target in targets:
It will be nice to actually enable this code and show the printed targets in the output.

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +   multiple quantum processors enabled today by GPU emulation.
```suggestion
   multiple quantum processors in parallel, enabled today by GPU emulation.
```

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +   feasible with any QPU today.
```suggestion
-  **nvidia-mgpu**: Allows for scaling circuit simulation on multiple GPUs, which is beyond what is
   feasible with any QPU today.
```

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Below we explore how to effectively utilize multi-GPU targets.
```suggestion
Below we explore how to effectively utilize multiple CUDA-Q targets with the same GHZ state preparation code
```

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Users will notice a **200x speedup** in executing the circuit below on
```suggestion
Users will notice a speedup of up to **2500x** in executing the circuit below on
```

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +The ``nvidia-mqpu`` backend allows for future workflows made possible
```suggestion
The ``nvidia-mqpu`` backend allows for future multi-QPUs workflows made possible
```

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Asynchronous data collection via circuit batching
This should be a subtitle

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/basics/run_kernel.rst
It will be nice to add printing out the circuit to the sample code (sample.py)

2024-06-03 20:56 UTC, efratshabtai commented on docs/sphinx/using/basics/run_kernel.rst
> +Sample Async
Please add the following paragraph (from [Executing Quantum Circuits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/executing_circuits.html)) to the top of the page, just before the 'Sample' subtitle: (make sure you keep the same format)
In CUDA-Q, quantum circuits are stored as quantum kernels. For estimating the probability distribution of a measured quantum state in a circuit, we use the sample function call, and for computing the expectation value of a quantum state with a given observable, we use the observe function call.

I think this is a good paragraph to add as you merge the two files into one.

2024-06-10 12:09 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +Classcial
Please do not greenlist words here without checking that they can be found in the dictionary. I assume this was meant to say "classical"? The spellchecker correctly flags this, and it needs to be removed here.

2024-06-10 12:10 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +Superpositions
To facilitate finding words in this list, our pipelines expect the entries in this file to be alphabetically sorted.

2024-06-10 12:11 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +cartesian
Please use the upper case spelling.

2024-06-10 12:12 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +cpu
Please use CPU instead.

2024-06-10 12:12 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +hadamard
Please use Hadamard instead.

2024-06-10 12:12 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +relizations
This is not a word.

2024-06-10 12:13 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +summarise
Please use US spelling (summarize)

2024-06-10 12:14 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +QPP
Please guard the code reference in the docs/comments with backticks instead of adding them here (`qpp`)

2024-06-10 12:14 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +qpp
see  other comment about qpp.

2024-06-10 12:14 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +probabilites
This is not a word.

2024-06-10 12:15 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +pauli
Please use upper casing.

2024-06-10 12:15 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +nvidia
Please use NVIDIA

2024-06-10 12:15 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +normalisation
Please use US spelling (normalization)

2024-06-10 12:20 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +mqpu
Please use backticks (\`) to guard code references (e.g. \`nvidia-mqpu\`)

2024-06-10 12:21 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +mgpu
same as for mqpu

2024-06-10 12:21 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +hamiltonians
Please use Hamiltonians instead.

2024-06-10 12:21 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +Async
Please use asynchronous instead.

2024-06-10 12:25 UTC, bettinaheim requested changes
See my comments regarding spelling.

2024-06-10 12:25 UTC, bettinaheim commented
/ok to test

2024-06-10 20:13 UTC, efratshabtai requested changes
Please take a look at my recent comments

2024-06-10 20:13 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Asynchronous Data Collection via Batching Hamiltonian Terms
The [original page](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multi_gpu_workflows.html#Asynchronous-data-collection-via-batching-Hamiltonian-terms) had 2 images showing a Hamiltonian breakdown to multiple terms, running on multiple devices.
Can you please also add it this page?
Images can be added to docs/sphinx/_static, see other pages on how they are referenced.

2024-06-10 21:52 UTC, WingCode commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Multi-GPU Workflows
Apologies, missed on this comment before. Will do

2024-06-14 17:56 UTC, efratshabtai commented on docs/sphinx/using/examples/multi_gpu_workflows.rst
> +Multi-GPU Workflows
Thank you @WingCode, please add the C++ snippets so we can conclude this PR and get you your bounty :)

2024-06-17 14:27 UTC, WingCode commented
@efratshabtai 
Sorry, could you please point me to the pages containing the C++ code snippets?

I have moved the python code to snippets or examples respectively. These are the pages mentioned in the [issue](https://github.com/NVIDIA/cuda-quantum/issues/1624) for which I checked for the c++ codes. Kindly find the page link and title/keyword where the code is present

1. [Quantum Bits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/quantum_bits.html)
Qubit - python
Pauli X gate - python
Superpositions & Measurements - python

2. [Multiple Qubits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multiple_qubits.html)
Some notation conventions - python
Controlled-NOT gate - python

3. [Multi-GPU Workflows](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multi_gpu_workflows.html)
get_targets - python
Available Targets - python
QPP-based CPU Backend - python
Acceleration via NVIDIA GPUs - python
Asynchronous data collection via batching Hamiltonian terms - python
Asynchronous data collection via circuit batching - python

4. [Multi-Control Synthesis](https://nvidia.github.io/cuda-quantum/latest/using/examples/multi_control.html).
[Previously linked with c++, python with right folders for examples and snippets
](https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/using/examples/multi_control.rst)

5. [Executing Quantum Circuits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/executing_circuits.html)
Sample - python
Sample Async - python
Observe - python

6. [Running your first CUDA-Q Program page](https://nvidia.github.io/cuda-quantum/latest/using/basics/run_kernel.html#)
[Previously linked with c++, python with right folders for examples and snippets](https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/using/basics/run_kernel.rst)

I will greatly appreciate the assistance

2024-06-17 15:57 UTC, efratshabtai commented
> @efratshabtai Sorry, could you please point me to the pages containing the C++ code snippets?
> 
> I have moved the python code to snippets or examples respectively. These are the pages mentioned in the [issue](https://github.com/NVIDIA/cuda-quantum/issues/1624) for which I checked for the c++ codes. Kindly find the page link and title/keyword where the code is present
> 
> 1. [Quantum Bits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/quantum_bits.html)
>    Qubit - python
>    Pauli X gate - python
>    Superpositions & Measurements - python
> 2. [Multiple Qubits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multiple_qubits.html)
>    Some notation conventions - python
>    Controlled-NOT gate - python
> 3. [Multi-GPU Workflows](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/multi_gpu_workflows.html)
>    get_targets - python
>    Available Targets - python
>    QPP-based CPU Backend - python
>    Acceleration via NVIDIA GPUs - python
>    Asynchronous data collection via batching Hamiltonian terms - python
>    Asynchronous data collection via circuit batching - python
> 4. [Multi-Control Synthesis](https://nvidia.github.io/cuda-quantum/latest/using/examples/multi_control.html).
>    [Previously linked with c++, python with right folders for examples and snippets
>    ](https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/using/examples/multi_control.rst)
> 5. [Executing Quantum Circuits](https://nvidia.github.io/cuda-quantum/latest/examples/python/tutorials/executing_circuits.html)
>    Sample - python
>    Sample Async - python
>    Observe - python
> 6. [Running your first CUDA-Q Program page](https://nvidia.github.io/cuda-quantum/latest/using/basics/run_kernel.html#)
>    [Previously linked with c++, python with right folders for examples and snippets](https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/using/basics/run_kernel.rst)
> 
> I will greatly appreciate the assistance

We currently don't have the C++ code for these 2 pages, they will need to be created. Is that something you will be able to do?
In general, every page under examples has both Python and C++ code snippets, while pages under applications are Python only.

2024-06-18 11:29 UTC, bettinaheim commented
> WingCode

@WingCode Could you please add a comment on the issue? I think if you do, I should be able to assign it to you. If that doesn't work, we'll have to temporarily add you as an outside collaborator before I can assign it.

2024-06-18 11:31 UTC, bettinaheim commented on .github/workflows/config/spelling_allowlist.txt
> +hamiltonians
```suggestion
```

2024-06-18 11:46 UTC, bettinaheim reviewed
This is a nice revision of the docs. Thanks!
I'll have to try out if the link change I suggest works and will come back to this PR on the 19th so that we can wrap it up.

2024-06-18 11:46 UTC, bettinaheim commented on docs/sphinx/using/backends/platform.rst
> +``sample`` can be a time intensive task. We can parallelize the
nit: 
```suggestion
Executing ``sample`` can be a time intensive task. We can parallelize the
```

2024-06-18 11:46 UTC, bettinaheim commented on docs/sphinx/using/backends/platform.rst
> +<https://nvidia.github.io/cuda-quantum/latest/api/languages/python_api.html#cudaq.sample_async:~:text=cudaq.observe_async(),%C2%B6>`__.
The issue with links like this is that they always point to the latest api docs even if one is currently browsing a different version of the docs. To keep the link pointing to the same docs version, I think you should be able to instead link it with
```
:func:`arguments it accepts<cudaq::observe_async>`
```
(I'll try this out shortly)

2024-06-18 11:49 UTC, bettinaheim commented
/ok to test

2024-06-19 11:32 UTC, WingCode commented
Regarding the failing of the snippets, the documentation was structured previously such way that

Instructions for step 1
....
#snippet 1
code for step 1
variable_1 created here.   
      
    

Instructions for step 2
...
#snippet 2
code for step 2
variable_1 referenced here (which is not available here)

So, how would we like to handle this? 
- Would we like to repeat the code for creation of variable_1 in the snippet 2
- Combine step 1 and step 2 into an example
I am open to suggestions :)

2024-06-19 16:18 UTC, bettinaheim commented
> Regarding the failure of the validate snippets test, the documentation was structured previously such way that
> 
> Instructions for step 1 .... #snippet 1 code for step 1 variable_1 created here.
> 
> Instructions for step 2 ... #snippet 2 code for step 2 variable_1 referenced here (which is not available here)
> 
> So, how would we like to handle this?
> 
> * Would we like to repeat the code for creation of variable_1 in the snippet 2
> * Combine step 1 and step 2 into an example
> 
> I am open to suggestions :)

Hi @WingCode I am taking a look and will get back to you shortly.

2024-06-19 17:07 UTC, bettinaheim commented on docs/sphinx/using/backends/platform.rst
> +<https://nvidia.github.io/cuda-quantum/latest/api/languages/python_api.html#cudaq.sample_async:~:text=cudaq.observe_async(),%C2%B6>`__.
I pushed the update to your branch.

2024-06-19 17:14 UTC, bettinaheim commented
/ok to test

2024-06-19 17:18 UTC, bettinaheim commented
@WingCode I updated your branch with the the necessary changes that should make the pipelines pass. This includes
- Fixing some file paths in the docs
- Linking within the same docs version rather to latest
- Fixing spelling issues
- Fixing formatting issues
- Removing timeit magic command from python code

Did you get a change to complete the update you wanted to have finished by the 19th or are you still working on it?

2024-06-19 17:58 UTC, WingCode commented
@bettinaheim Thank you very much for your support! I would prefer merging this MR to main and closing this issue.

Other changes I would like to implement can be handled as iterative improvements in a new MR. I look forward to your recommendation.

2024-06-19 18:47 UTC, bettinaheim commented
> @bettinaheim Thank you very much for your support! I would prefer merging this MR to main and closing this issue.
> 
> Other changes I would like to implement can be handled as iterative improvements in a new MR. I look forward to your recommendation.

I am good with that. While I have pushed updates to get you past the pipeline specific things, I haven't pushed the update to what I think you meant with your original question; 

The reason we have code snippets in .py files rather than directly in rst files is that we actually tests that these files indeed run correctly as part of our pipelines. Hence, if you have something like

> Instructions for step 1 .... #snippet 1 code for step 1 variable_1 created here.
> 
> Instructions for step 2 ... #snippet 2 code for step 2 variable_1 referenced here (which is not available here)

the idea is to not create two snippets, but rather one snippet file that contains a fully valid code including both step 1 and step 2, and then only include the relevant line numbers for each step in the code block in the rst file. You can see an example of this in [first_observe.py](https://github.com/NVIDIA/cuda-quantum/blob/main/docs/sphinx/snippets/python/using/first_observe.py), where the relevant lines are marked with comments (e.g. #[Begin Observe2]), which are then used to include only these lines in the docs:

```
  .. literalinclude:: ../../snippets/python/using/first_observe.py
        :language: python
        :start-after: [Begin Observe2]
        :end-before: [End Observe2]
```
 
@WingCode Let me know if that clarifies things, and if you can give it a go to merge all the individual snippets you created into a working file and include only the desired lines for each description in the docs. Once you have done that, this should be good to go.

2024-06-19 18:48 UTC, bettinaheim commented
/ok to test

2024-06-19 19:02 UTC, WingCode commented
@bettinaheim Thank you for the clarification and detailed explanation. I will merge snippets and update the references 👍

2024-06-19 19:21 UTC, bettinaheim commented
/ok to test

2024-06-19 20:05 UTC, WingCode commented
@bettinaheim I have merged the snippets and updated the refs.

2024-06-19 20:18 UTC, bettinaheim commented
/ok to test

2024-06-19 20:21 UTC, bettinaheim commented
/ok to test

2024-06-19 21:13 UTC, bettinaheim commented
/ok to test

2024-06-20 14:01 UTC, bettinaheim commented
/ok to test

2024-06-20 14:16 UTC, bettinaheim commented
/ok to test

2024-06-20 16:45 UTC, bettinaheim commented
/ok to test

2024-06-20 17:46 UTC, bettinaheim commented
/ok to test

2024-06-20 18:56 UTC, merged