Enable custom unitary operations in Python for simulation
NVIDIA/cuda-quantum pull request #1781
Opened 2024-06-08 20:17 UTC by khalatepradnya

Python support for custom operations using new API - `cudaq.register_operation`

This first PR focuses solely on Python frontend and simulation, and follow up PRs will cover decomposition (synthesis)

2024-06-10 15:21 UTC, schweitzpgi requested changes
I don't see a C++ test or changes to the C++ bridge.

Is unitary circuit synthesis part of another PR?

2024-06-10 15:47 UTC, khalatepradnya commented
Thanks, Eric, for the comments. I will address these.
The C++ MLIR support will be part of a separate PR but will depend on this, like `QuakeOps`.

2024-06-10 23:44 UTC, khalatepradnya commented on include/cudaq/Optimizer/Dialect/Quake/QuakeOps.td
> +  let arguments = (ins StrAttr:$opName,
Will be addressed in https://github.com/NVIDIA/cuda-quantum/pull/1794.
I will update this after that PR.

2024-06-22 07:38 UTC, khalatepradnya commented
Covered by https://github.com/NVIDIA/cuda-quantum/pull/1794

2024-06-22 07:38 UTC, closed without merging