Temporary fix for AST visitor reentrancy bugs.
NVIDIA/cuda-quantum pull request #22
Opened 2023-03-23 20:32 UTC by schweitzpgi

2023-04-03 00:15 UTC, amccaskey approved these changes

2023-04-03 08:38 UTC, bettinaheim requested changes
The requested changes are adding regression testss.

2023-04-04 07:29 UTC, bettinaheim commented on lib/Frontend/nvqpp/ConvertType.cpp
> +  QuakeBridgeVisitor vis(*this);
Ok, let's track this under switching to libstdc++-12 then. 
Are the current tests covering the failure we saw, i.e. are the current tests failing without this fix?

I created an issue for the libstdc++ 12 update here: https://github.com/NVIDIA/cuda-quantum/issues/57. This PR should take care of the first item in the task list there. I can take care of the rest, if nothing else in the compiler needs to change. Let's switch to gcc12 then for the pipeline - this switch should be relevant only for us, and not matter for using CUDA Quantum, such that we don't need a deprecation strategy for 11.

2023-04-04 07:32 UTC, bettinaheim commented
@schweitzpgi One more question: Could you clarify what exactly is "temporary" about the fix and should change in the future?

2023-04-04 18:26 UTC, schweitzpgi commented
> @schweitzpgi One more question: Could you clarify what exactly is "temporary" about the fix and should change in the future?

I should write up a RFC. Longer term, we want the bridge to be able to construct and use types as part of the traversal (single pass). At the moment, there are two semi-independent and not necessarily related traversals happening and the type being generated (hopefully) agrees with the code generated. So the current state is awkward.

2023-04-04 20:25 UTC, merged